name: Build and deploy to production

on: 
  push:
    branches: 
      - main

env:
  APP_SERVICE_NAME: hello-with-flask2
  DOCKER_IMAGE: flaskwebapp
  DOCKER_TAG: "1.0.0"
      
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    
    - name: Checkout GitHub Actions
      uses: actions/checkout@main
        
    - name: Login to Azure Container Registry
      uses: azure/docker-login@v1
      with:
        login-server: ${{secrets.ACR_HOST }}
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
     
     
    - name: Build and push container image to registry 
      id: container-registry
      uses: mr-smithers-excellent/docker-build-push@v5.5
      with: 
        image: ${{env.DOCKER_IMAGE}}
        registry: ${{secrets.ACR_HOST }}
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
        tags: ${{env.DOCKER_TAG}}
        
        
    - name: Deploy to App Service
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{env.APP_SERVICE_NAME}}
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        images: ${{secrets.ACR_HOST }}/${{env.DOCKER_IMAGE}}:${{ env.DOCKER_TAG }}