name: Build and deploy to production

on: 
  push:
    branches: 
      - main

env:
  APP_SERVICE_NAME: hello-with-flask
  DOCKER_IMAGE: flaskwebapp
  DOCKER_TAG: v1
  ACR_HOST: decisionenginecontainerregistry.azurecr.io
      
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Build and Push Image
      id: container-registry
      uses: mr-smithers-excellent/docker-build-push@v5.5
      with: 
        image: ${{env.DOCKER_IMAGE}}
        tags: ${{env.DOCKER_TAG }}
        registry: ${{env.ACR_HOST }}
        username: DecisionEngineContainerRegistry
        password: iM3ApzubGlpD/KDHbwN9Y32IIVPOILG0

  deploy:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{env.APP_SERVICE_NAME}}
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        images: ${{env.ACR_HOST }}/${{env.DOCKER_IMAGE}}:${{env.DOCKER_TAG }}    